name: voting_app
description: Flux DigiPol pre-alpha app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 0.1.2

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  # statusbarcolor has an issue with a badly typed int; not sure if it was breaking the build or just a warning
  flutter_statusbarcolor: 0.2.1
  bip39: ^1.0.3
  # instabug_flutter:
  cupertino_icons: ^1.0.0
  pdf_viewer_plugin: ^1.0.0+2
  pdf: ^1.11.2
  path_provider: ^1.6.18
  http: ^0.12.2
  provider: ^4.3.2+2
  web3dart: ^1.2.3
  get_it: ^5.0.1
  bip32: ^1.0.5
  shared_preferences: ^0.5.12
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  url_launcher: ^5.7.2
  dots_indicator: ^1.2.0
  convert: ^2.1.1
  fl_chart: ^0.11.1
  flutter_svg: ^0.18.0
  dartz: ^0.9.1
  adt_annotation: ^0.2.0
  #auto_route:

# Why is this here? -MK
#dependency_overrides:
#  analyzer: "0.39.14"

dev_dependencies:
  build_resolvers: ^1.3.0
  flutter_test:
     sdk: flutter
  flutter_launcher_icons: ^0.8.0
  build_runner: ^1.10.1
  hive_generator: ^0.7.2+1
  adt: ^0.4.0
  test: any
  # auto_route_generator:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/graphics/icon-ios-android.png"
  adaptive_icon_background: "#FDF7B9"
  adaptive_icon_foreground: "assets/graphics/icon-adaptive-foreground-android.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/bills_out.json
    - assets/graphics/undraw_check_boxes_m3d0.svg
    - assets/graphics/undraw_ethereum_fb7n.svg
    - assets/graphics/undraw_my_app_grf2.svg
    - assets/graphics/undraw_voting_nvu7.svg
    - assets/graphics/undraw_new_ideas_jdea.svg
    - assets/graphics/undraw_process_e90d.svg
    - assets/graphics/undraw_Hello_qnas.svg
    - assets/data/sample_bills.json
    - assets/data/sample_issues.json
    - assets/data/sample_user.json
    - assets/data/sample_bill.json
    - assets/contracts/voting.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
